local Rarity = {
    Common = {
        name = "Common",
        description = "Common rarity",
        color = Color3.fromRGB(255, 255, 255),
    },
    Rare = {
        name = "Rare",
        description = "Rare rarity",
        color = Color3.fromRGB(0, 255, 0),
    },
    Epic = {
        name = "Epic",
        description = "Epic rarity",
        color = Color3.fromRGB(0, 0, 255),
    },
    Legendary = {
        name = "Legendary",
        description = "Legendary rarity",
        color = Color3.fromRGB(255, 255, 0),
    },
    Mythic = {
        name = "Mythic",
        description = "Mythic rarity",
        color = Color3.fromRGB(255, 0, 255),
        gradient = "",
    },
}

return Rarity